// flow-typed signature: be8b4a3f6ce263f768444f8a8542e3e5
// flow-typed version: <<STUB>>/pretty-hrtime_v^1.0.3/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pretty-hrtime'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pretty-hrtime' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'pretty-hrtime/index' {
  declare module.exports: $Exports<'pretty-hrtime'>;
}
declare module 'pretty-hrtime/index.js' {
  declare module.exports: $Exports<'pretty-hrtime'>;
}
