// flow-typed signature: 9158089734d223dbf63f8105a985fa94
// flow-typed version: <<STUB>>/stack-trace_v0.0.10/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stack-trace'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stack-trace' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stack-trace/lib/stack-trace' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stack-trace/lib/stack-trace.js' {
  declare module.exports: $Exports<'stack-trace/lib/stack-trace'>;
}
