// flow-typed signature: c7b1e7fac3a704a6c96b44fdf94790fc
// flow-typed version: <<STUB>>/subdir_v0.0.3/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'subdir'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'subdir' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'subdir/example/inside' {
  declare module.exports: any;
}

declare module 'subdir/test/inside' {
  declare module.exports: any;
}

// Filename aliases
declare module 'subdir/example/inside.js' {
  declare module.exports: $Exports<'subdir/example/inside'>;
}
declare module 'subdir/index' {
  declare module.exports: $Exports<'subdir'>;
}
declare module 'subdir/index.js' {
  declare module.exports: $Exports<'subdir'>;
}
declare module 'subdir/test/inside.js' {
  declare module.exports: $Exports<'subdir/test/inside'>;
}
